name: Install Tools & Dependencies
description: Installs pnpm, JS runtime & package dependencies

inputs:
  node-version:
    description: 'Node version'
    required: false
    default: 16
  js-runtime:
    description: 'JS runtime'
    required: false
    default: 'node'
  install-dependencies:
    description: 'Install dependencies'
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Temp output
      run: |
        echo "node-version ${{ inputs.node-version }}"
        echo "js-runtime ${{ inputs.js-runtime }}"
        echo "install-dependencies ${{ inputs.install-dependencies }}"
        echo "install-dependencies ${{ inputs.install-dependencies == false }}"
        echo "install-dependencies ${{ inputs.install-dependencies == 'false' }}"
      shell: bash

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Use Deno
      if: ${{ inputs.js-runtime == 'deno' }}
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.26.1

    - name: Install dependencies
      if: ${{ inputs.install-dependencies }}
      run: pnpm install
      shell: bash
