name: Benchmark

on:
  issue_comment:
    types: [created]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  FORCE_COLOR: true

jobs:
  benchmark:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '!bench') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      PR-BENCH: ${{ steps.benchmark-pr.outputs.BENCH_RESULT }}
      MAIN-BENCH: ${{ steps.benchmark-main.outputs.BENCH_RESULT }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{github.event.pull_request.head.sha}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm run build

      - name: Get bench command
        id: bench-command
        run: |
          benchcmd=$(echo "${{ github.event.comment.body }}" | grep '!bench' | awk -F ' ' '{print $2}')
          echo "bench=$benchcmd >> $GITHUB_OUTPUT"
        shell: bash

      - name: Run benchmark
        id: benchmark-pr
        run: |
          result=$(pnpm run --silent benchmark ${{ steps.bench-command.outputs.bench }} --title "**PR**")
          processed=$(node ./benchmark/ci-helper.js "$result")
          echo "BENCH_RESULT=$processed >> $GITHUB_OUTPUT"
          echo "$processed"
        shell: bash

      # main benchmark
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: "main"

      - name: Install
        run: |
          pnpm install

      - name: Build Packages
        run: pnpm run build

      - name: Run benchmark
        id: benchmark-main
        run: |
          result=$(pnpm run --silent benchmark ${{ steps.bench-command.outputs.bench }} --title "**MAIN**")
          processed=$(node ./benchmark/ci-helper.js "$result")
          echo "BENCH_RESULT=$processed >> $GITHUB_OUTPUT"
          echo "$processed"
        shell: bash

  output-benchmark:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '!bench') }}
    needs: [benchmark]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.issue.number }}
          message: |
            ${{ needs.benchmark.outputs.PR-BENCH }}

            ${{ needs.benchmark.outputs.MAIN-BENCH }}
