name: CI

on:
  push:
    branches:
      - actions
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'
      - 'examples/**'
      - 'www/**'

jobs:
  build:
    name: Build Packages
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install NPM Dependencies
        run: yarn install --frozen-lockfile --ignore-engines --registry https://registry.npmjs.org --network-timeout 300000

      - name: Build Packages
        run: yarn build:all

      - name: Upload Package Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: packages/**/dist/*
          if-no-files-found: error
  
  test:
    name: 'Test: node-${{ matrix.node_version }}, ${{ matrix.os }}'
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12, 14, 16]
        include:
          - os: windows-latest
            node_version: 16
          - os: macos-latest
            node_version: 16
      fail-fast: false
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node@${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2

      - name: Print Package Artifacts
        run: ls -R artifacts/

      - name: Copy Artifacts
        shell: bash
        run: |
          cd artifacts
          mkdir -p ../tmp/packages
          mv * ../tmp/packages
          cd ../tmp
          tar -cvzpf artifacts.tar.gz *
          mv artifacts.tar.gz ../artifacts.tar.gz
          cd ..
          tar -xvzpf artifacts.tar.gz
          rm -rf artifacts
          rm -rf tmp
          rm -f artifacts.tar.gz

      - name: Install NPM Dependencies
        run: yarn install --frozen-lockfile --ignore-engines --registry https://registry.npmjs.org --network-timeout 300000

      - name: Test
        run: yarn test
