name: CI

on:
  push:
    branches:
      - actions
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'
      - 'examples/**'
      - 'www/**'

jobs:
  build:
    name: Build Packages
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install NPM Dependencies
        run: yarn install --frozen-lockfile --ignore-engines --registry https://registry.npmjs.org --network-timeout 300000

      - name: Build Packages
        run: yarn build:all

      - name: Upload Package Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: astro
          path: |
            packages/astro/**/*
            !**/node_modules
            !packages/astro/src/**/*
            !packages/astro/test/**/*
            !packages/astro/tsconfig.json
          if-no-files-found: error
