name: 'Update Latest from main'

on:
  push:
    branches:
      - "main"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update:
    name: check for updates in .changeset
    runs-on: ubuntu-latest
    steps:
      - name: checkout git branch
        uses: actions/checkout@v2

      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD
          
          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file == .changeset/* ]]; then
              echo "This modified file is under the 'changeset' folder."
              echo "::set-output name=run_job::true"
              break
            else
              echo "::set-output name=run_job::false"
            fi
          done < files.txt

  update_latest_branch:
    name: Update the latest branch
    needs: update
    if: needs.update.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: latest
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Update Latest: ({sha}) {msg}" # The commit message
