name: Preview release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '!**' 
  merge_group:
  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "**/*.md"
      - ".github/ISSUE_TEMPLATE/**"
        
permissions:
  contents: read
  actions: write
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  FORCE_COLOR: true
  ASTRO_TELEMETRY_DISABLED: true
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  preview:
    name: Publish preview release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Disable git crlf
        run: git config --global core.autocrlf false
  
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
  
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
  
      - name: Install dependencies
        run: pnpm install
  
      - name: Build Packages
        run: pnpm run build
  
      - name: Publish packages
        run: pnpx pkg-pr-new publish --pnpm './packages/*' './packages/integrations/*'
