name: 'Update Latest from main'

on:
  push:
    branches:
      - "main"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update:
    name: check for updates in .changeset
    runs-on: ubuntu-latest
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    steps:
      - name: checkout git branch
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: yarn
      
      - name: check modified files
        id: check_files
        run: npx changeset status --output ./status.json

      - name: check output
        run: | 
          output=`echo $(cat status.json)`
          if [[ $output = '{ "changesets": [], "releases": [] }' ]]
          then
              echo "::set-output name=run_job::false"
          else
            echo "::set-output name=run_job::false"
          fi
            echo $output


  update_latest_branch:
    name: Update the latest branch
    needs: update
    if: needs.update.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: latest
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Update Latest: ({sha}) {msg}" # The commit message